######################################################################
# Automatically generated by qmake (2.01a) Mon May 14 08:58:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
QT += network

# Input
HEADERS += DLockLocal.hpp DLockManager.hpp
SOURCES += main.cpp DLockManager.cpp DLockLocal.cpp
